### PR TITLE
Fix: Linux hosts cannot build images

### LINKED ISSUE #14: Podman exits with error: `Error: executing /usr/bin/podman-compose run --build rpi_imagegen bash -c `
Running the `./generate.sh` script as a super-user, with [--remove-orphans removed](https://github.com/uniclogs/uniclogs-linux/issues/12), podman exits with the following error:

```bash
Generating image...0:00:16
[03:19:46] /home/imagegen/rpi-image-gen/image[post-image.sh] /home/imagegen/rpi-image-gen/work/rpi_uniclogs/deploy
[03:19:46] Deploying image and SBOM
*** Zstandard CLI (64-bit) v1.5.4, by Yann Collet ***
/home/imagegen/rpi-image-gen/work/rpi_uniclogs/artefacts/rpi_uniclogs.img : 35.45%   (   577 MiB =>    205 MiB, /home/imagegen/rpi-image-gen/work/rpi_uniclogs/deploy/rpi_uniclogs.img.zst) 
*** Zstandard CLI (64-bit) v1.5.4, by Yann Collet ***
/home/imagegen/rpi-image-gen/work/rpi_uniclogs/artefacts/rpi_uniclogs.img.sparse : 40.03%   (   504 MiB =>    202 MiB, /home/imagegen/rpi-image-gen/work/rpi_uniclogs/deploy/rpi_uniclogs.img.sparse.zst) 
*** Zstandard CLI (64-bit) v1.5.4, by Yann Collet ***
/home/imagegen/rpi-image-gen/work/rpi_uniclogs/artefacts/rpi_uniclogs.sbom : 11.24%   (  11.1 MiB =>   1.25 MiB, /home/imagegen/rpi-image-gen/work/rpi_uniclogs/deploy/rpi_uniclogs.sbom.zst) 
[SUCCESS] Image build completed successfully!
cp: cannot create regular file './rpi_uniclogs.img.sparse.zst': Permission denied
cp: cannot create regular file './rpi_uniclogs.img.zst': Permission denied
cp: cannot create regular file './rpi_uniclogs.sbom.zst': Permission denied
Error: executing /usr/bin/podman-compose run --build rpi_imagegen bash -c 
        /home/imagegen/scripts/generate-image.sh
    : exit status 1
```
Entering the container using `sudo podman run -it localhost/rpi-imagegen:latest` and running `./build.sh`, another error can be found:

```bash
Module binfmt_misc not loaded in host
Please run:
  sudo modprobe binfmt_misc
```

There is no kernel module available to me as `binfmt_misc` on Arch Linux, but binfmt seems to be configured properly on my system, the output of running `mount | grep "binfmt"` is

```bash
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=42,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=9982)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
```

And the status of each systemd service (`proc-sys-fs-binfmt_misc.mount`, `systemd-binfmt.service`, and `proc-sys-fs-binfmt_misc.automount`) are all active and seem normal.

Let me know if anymore information is needed.

System info: 
OS: Arch Linux x86_64
Kernel: Linux 6.12.51-1-lts

### PR DESCRIPTION
**Pull request by bryborge**
This work fixes some minor issues when attempting to run image generation in a podman container on a linux host.  This has also been tested on macOS ✅ 

This should also fix https://github.com/uniclogs/uniclogs-linux/issues/14

### CODE REVIEW

File: container/Containerfile [hunk 1]
```diff
@@ -16,17 +16,15 @@ RUN curl -L -o rpi-image-gen.tar.gz https://github.com/raspberrypi/rpi-image-gen
     && mv rpi-image-gen-${RPIIG_GIT_SHA} /rpi-image-gen \
     && rm rpi-image-gen.tar.gz
 
-RUN <<EOF
-arch=$(uname -m);
-if [ "$arch" != "aarch64" ] || [ "$arch" != "arm64" ]; then
-    apt-get install --no-install-recommends -y qemu-user-static;
+RUN arch=$(uname -m) \
```
Comment (bryborge) [inline container/Containerfile:19]: I was having issues with the <<EOF syntax and got tired of wrestling with it, which is why this chunk of code got modified.

File: scripts/build-env.sh [hunk 2]
```diff
@@ -18,9 +18,15 @@ main() {
...
-    "
+
+    sudo podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes -c yes
+    sudo podman build -t rpi-imagegen:latest -f container/Containerfile .
+
+    mkdir -p "$PROJECT_ROOT/build"
+    sudo chmod 777 "$PROJECT_ROOT/build"
+
+    print_info "Running image generation (requires sudo for privileged operations) ..."
+    exec sudo podman compose run --rm rpi_imagegen bash -c "/home/imagegen/scripts/generate-image.sh"
```
Comment (bryborge) [inline scripts/build-env.sh:29]: On macOS, this was not required, but on a linux host, it is necessary.

**Review by ThirteenFish — APPROVED** [review]
Looks good.
